import Head from 'next/head'
import { useState } from 'react'
import Cabecalho from './components/Cabecalho'
import ContainerCard from './components/ContainerCard'
import Card from './components/Card'

export default function Home() {

  let text = ""

  return (
    <>
      <Head>
        <title>Fazenda Orgânica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Cabecalho/>
      </header>
      <main>
        <ContainerCard>
          <Card
          title={"Gado de Corte"}
          img={"/gado.png"}
          text="Em nossa produção de gado de corte, dedicamos cuidado e atenção a cada etapa do processo. 
          Nossos animais são criados em pastagens amplas e bem-mantidas, 
          permitindo que se desenvolvam de maneira saudável e natural."
        />
        <Card
          title={"Caprinos"}
          img={"/caprino.png.png"}
          text="Nossos animais são criados em um ambiente que respeita suas características naturais, 
           proporcionando espaço adequado para movimentação e pastagem.
           Através de um manejo atencioso e nutrição balanceada, 
           garantimos o desenvolvimento saudável e vigoroso de nossos caprinos"
        />
        <Card
          title={"Produção de ovos"}
          img={"/ovos.png.png"}
          text="Em nossa produção de ovos, primamos pela qualidade e segurança alimentar. 
          Nossas galinhas são criadas em ambientes confortáveis e higiênicos, 
          recebendo uma dieta balanceada e cuidados veterinários regulares."
        />
         <Card
          title={"Produção de Uva"}
          img={"/uva.png.png"}
          text="Na nossa produção de uva, dedicamos toda nossa paixão à criação de frutos excepcionais. 
          Cada videira é cultivada com cuidado e atenção, em harmonia com o solo e o clima da região. 
          Utilizamos práticas agrícolas sustentáveis para preservar a saúde do ambiente e garantir uvas de qualidade superior."
        />
         <Card
          title={"Produção de Tomate"}
          img={"/tomate.png.png"}
          text="Em nossa produção de tomates, cultivamos uma paixão pelo sabor e pela qualidade. 
          Cada planta é cuidadosamente selecionada e cultivada para garantir frutos suculentos e cheios de sabor. 
          Utilizamos métodos de cultivo responsáveis, 
          priorizando práticas que respeitam o solo e o meio ambiente."
        />
         <Card
          title={"Produção de Laranja"}
          img={"/laranja.png.png"}
          text="Na nossa produção de laranjas, cultivamos um compromisso com a qualidade e o sabor. 
          Nossas laranjeiras são cuidadosamente mantidas em um ambiente propício, 
          beneficiando-se do clima e solo ideais para seu crescimento saudável. "
        />
         <Card
          title={"Hortifruti"}
          img={"/hortifruti.png.png"}
          text="Nosso hortifrúti é resultado de um compromisso constante com a qualidade e o frescor. 
          Cada fruta e vegetal é selecionado cuidadosamente para garantir que você tenha acesso aos melhores produtos da natureza."
        />
        </ContainerCard>
      </main>
    </>
  )
}